In [7]:
import fitz
import os

In [8]:
def extract_pdf_text(file_path):
    text = ""
    
    pdf = fitz.open(file_path)
    
    for page in pdf:
        text += page.get_text()
    
    return text

In [9]:
file_path = "../data/raw/nda_1.pdf"

contract_text = extract_pdf_text(file_path)

print(contract_text[:2000])

Mutual NDA – revised 4 May 2018
1
Barclays Commercial, Innovation & Technology Legal
______________________________________
NON-DISCLOSURE AGREEMENT
______________________________________
Note: This document is a Non-Disclosure Agreement only. A separate contract will be required
whenever:
-
goods or services are being provided by or to Barclays;
-
any payment is being made by or to Barclays;
-
any personal data is being transferred by or to Barclays; or
-
any intellectual property is being created or licensed by either party to the other (including
any rights to use Barclays’ name or logo).
Barclays:
Name and company registration
number:
(choose
the
applicable
Barclays contracting entity)
Registered address:
1 Churchill Place, London, E14 5HP
Counterparty:
Name:
(Full corporate or personal name of
other party)
Registered
address:
(or
home
address where individual)
Country of registration: (leave
blank where counterparty is an
individual)
Company registration number:
(leave blank where counterparty is an
individual)
Effective Date:
(Date from which information is first being disclosed under this
agreement – this can start before, after or on the date of
signature)
Project:
(Details of the proposal/project to which this agreement applies,
e.g. “Evaluations by Barclays of the Counterparty’s [X] product”,
“Discussions for the development of an alternative [Y] system”,
“Discussions on how Barclays can collaborate with [X] for the
purposes of [Y]”)
Barclays and the Counterparty have entered into discussions regarding the Project and it is envisaged
that each party may from time to time receive Information (as defined below) relating to the other in
respect thereof. The parties have agreed that any dealings between them shall be subject to this
Agreement, the terms of which are contained on the following pages.
Executed by the parties or their respective duly authorised representatives on the date of this
Agreement.
For and on behalf of Barclays:
For and on behalf of t

In [10]:
output_path = "../data/processed/nda_1.txt"

with open(output_path, "w", encoding="utf-8") as file:
    file.write(contract_text)

print("Text saved successfully")

Text saved successfully

In [11]:
input_folder = "../data/raw/"
output_folder = "../data/processed/"

for filename in os.listdir(input_folder):
    if filename.endswith(".pdf"):
        file_path = os.path.join(input_folder, filename)

        text = extract_pdf_text(file_path)

        output_path = os.path.join(
            output_folder,
            filename.replace(".pdf", ".txt")
        )

        with open(output_path, "w", encoding="utf-8") as file:
            file.write(text)

print("All contracts extracted successfully")

All contracts extracted successfully

In [12]:
def clean_text(text):
    text = text.replace("\n", " ")
    text = text.replace("\t", " ")
    text = " ".join(text.split())
    return text

In [13]:
cleaned_text = clean_text(contract_text)

print(cleaned_text[:2000])

Mutual NDA – revised 4 May 2018 1 Barclays Commercial, Innovation & Technology Legal ______________________________________ NON-DISCLOSURE AGREEMENT ______________________________________ Note: This document is a Non-Disclosure Agreement only. A separate contract will be required whenever: - goods or services are being provided by or to Barclays; - any payment is being made by or to Barclays; - any personal data is being transferred by or to Barclays; or - any intellectual property is being created or licensed by either party to the other (including any rights to use Barclays’ name or logo). Barclays: Name and company registration number: (choose the applicable Barclays contracting entity) Registered address: 1 Churchill Place, London, E14 5HP Counterparty: Name: (Full corporate or personal name of other party) Registered address: (or home address where individual) Country of registration: (leave blank where counterparty is an individual) Company registration number: (leave blank where counterparty is an individual) Effective Date: (Date from which information is first being disclosed under this agreement – this can start before, after or on the date of signature) Project: (Details of the proposal/project to which this agreement applies, e.g. “Evaluations by Barclays of the Counterparty’s [X] product”, “Discussions for the development of an alternative [Y] system”, “Discussions on how Barclays can collaborate with [X] for the purposes of [Y]”) Barclays and the Counterparty have entered into discussions regarding the Project and it is envisaged that each party may from time to time receive Information (as defined below) relating to the other in respect thereof. The parties have agreed that any dealings between them shall be subject to this Agreement, the terms of which are contained on the following pages. Executed by the parties or their respective duly authorised representatives on the date of this Agreement. For and on behalf of Barclays: For and on behalf of the

In [14]:
cleaned_output_path = "../data/processed/cleaned_nda_1.txt"

with open(cleaned_output_path, "w", encoding="utf-8") as file:
    file.write(cleaned_text)

print("Cleaned text saved successfully")

Cleaned text saved successfully

In [15]:
import re

def split_clauses(text):
    clauses = re.split(r'\.\s+', text)

    return clauses

In [16]:
clauses = split_clauses(cleaned_text)

print(clauses[:10])

['Mutual NDA – revised 4 May 2018 1 Barclays Commercial, Innovation & Technology Legal ______________________________________ NON-DISCLOSURE AGREEMENT ______________________________________ Note: This document is a Non-Disclosure Agreement only', 'A separate contract will be required whenever: - goods or services are being provided by or to Barclays; - any payment is being made by or to Barclays; - any personal data is being transferred by or to Barclays; or - any intellectual property is being created or licensed by either party to the other (including any rights to use Barclays’ name or logo)', 'Barclays: Name and company registration number: (choose the applicable Barclays contracting entity) Registered address: 1 Churchill Place, London, E14 5HP Counterparty: Name: (Full corporate or personal name of other party) Registered address: (or home address where individual) Country of registration: (leave blank where counterparty is an individual) Company registration number: (leave blank where counterparty is an individual) Effective Date: (Date from which information is first being disclosed under this agreement – this can start before, after or on the date of signature) Project: (Details of the proposal/project to which this agreement applies, e.g', '“Evaluations by Barclays of the Counterparty’s [X] product”, “Discussions for the development of an alternative [Y] system”, “Discussions on how Barclays can collaborate with [X] for the purposes of [Y]”) Barclays and the Counterparty have entered into discussions regarding the Project and it is envisaged that each party may from time to time receive Information (as defined below) relating to the other in respect thereof', 'The parties have agreed that any dealings between them shall be subject to this Agreement, the terms of which are contained on the following pages', 'Executed by the parties or their respective duly authorised representatives on the date of this Agreement', 'For and on behalf of Barclays: For and on behalf of the Counterparty: Signature: Name: Title: Date: Barclays Services Limited (Registered Number 01767980) Barclays Bank PLC (Registered Number 1026167) Barclays Bank UK PLC (Registered Number 09740322) Mutual NDA – revised 4 May 2018 2 Barclays Commercial, Innovation & Technology Legal TERMS OF NON-DISCLOSURE AGREEMENT 1 Definitions and Interpretation 1.1 In this Agreement the following definitions shall apply: Affiliate means, in relation to a party, any person or entity Controlling, Controlled by or under common Control with such party from time to time; Barclays Competitor means any bank or building society, or any other entity that carries on banking services, insurance services, credit or debit card issuing, card acquiring services, payment services, asset management or investment banking, or any entity Controlled by, Controlling, or under common Control of, any such entity; Confidential Information means Information relating to one party or any of its Related Parties (Disclosing Party) (and/or the business carried on or proposed or intended to be carried on by the Disclosing Party) which is made available in connection with the Project to the other party (Receiving Party) (or any of its Related Parties) by the Disclosing Party (or any of its Related Parties), whether on or after the Effective Date, including any information, analysis or specifications derived from, containing or reflecting such information, but excluding any Information that the Receiving Party could not reasonably be expected to consider to be confidential or commercially sensitive; Control means the power, direct or indirect, to direct or cause the direction of the management and policies of such entity whether by contract, ownership of shares, membership of the board of directors, agreement or otherwise and, in any event and without limitation of the foregoing, any entity owning more than 30% of the voting securities of a second entity shall be deemed to control that second entity', 'The terms Controlling and Controlled shall have a corresponding meaning; Information means all information including, without limitation, any Intellectual Property Rights, information relating to systems, operations, plans, intentions, market opportunities, customers, suppliers, know-how, trade secrets and business affairs, business methods and business concepts in whatever form, whether in oral, tangible or in documented form and, if in tangible or documented form, whether marked or identified as being proprietary or not; Intellectual Property Rights means: (a) any copyright, design rights, patents, Inventions, logos, business names, service marks and trade marks, Internet domain names, moral rights, rights in databases, data, source codes, reports, drawings, specifications, know how, business methods, trade secrets, semi-conductor rights, topography rights, whether registered or unregistered, rights in the nature of unfair competition and the right to sue for passing off; (b) applications for registration and the right to apply for registration for any of these rights; and (c) all other intellectual property rights and equivalent or similar forms of protection, existing anywhere in the world; Invention means any invention, idea, discovery, development, improvement or innovation made, whether or not patentable or capable of registration, and whether or not recorded in any medium; Permitted Purpose means any discussions or negotiations between the parties concerning the Project; Related Party means, in relation to either party, any Affiliate of that party, or any director, officer, employee, agent, professional adviser (including solicitors, auditors, insurers and accountants), contractor or subcontractor of that party or of any Affiliate of that party', '2 Confidential Information 2.1 The Receiving Party shall treat and keep all Confidential Information as secret and confidential and will not, without the Disclosing Party’s written consent, directly or indirectly communicate or disclose (whether in writing or orally or in any other manner) Confidential Information to any other person other than in accordance with the terms of this Agreement', '2.2 The Receiving Party shall only use the Confidential Information for the Permitted Purpose']

In [17]:
print("Total clauses:", len(clauses))

Total clauses: 51

In [18]:
import pandas as pd
df = pd.DataFrame({"clause": clauses})
df.to_csv("../data/datasets/clauses.csv", index=False)
print("Clauses saved successfully")

Clauses saved successfully

In [19]:
df.head(20)

                                               clause
0   Mutual NDA – revised 4 May 2018 1 Barclays Com...
1   A separate contract will be required whenever:...
2   Barclays: Name and company registration number...
3   “Evaluations by Barclays of the Counterparty’s...
4   The parties have agreed that any dealings betw...
5   Executed by the parties or their respective du...
6   For and on behalf of Barclays: For and on beha...
7   The terms Controlling and Controlled shall hav...
8   2 Confidential Information 2.1 The Receiving P...
9   2.2 The Receiving Party shall only use the Con...
10  2.3 Notwithstanding clauses 2.1 and 2.2, the R...
11  2.4 The Receiving Party shall at all times rem...
12  2.5 If any Confidential Information is copied,...
13  2.6 Notwithstanding whether or not the Receivi...
14  2.7 The Disclosing Party warrants and represen...
15  2.8 If there is a change of Control of the Cou...
16  3 Exceptions 3.1 The provisions of clause 2 (C...
17  3.2 Confidential Information shall not be exem...
18  4 Records and return of information 4.1 The Re...
19  The Receiving Party shall not make any copies ...

In [20]:
df["label"] = ""
df.head(20)

                                               clause label
0   Mutual NDA – revised 4 May 2018 1 Barclays Com...
1   A separate contract will be required whenever:...
2   Barclays: Name and company registration number...
3   “Evaluations by Barclays of the Counterparty’s...
4   The parties have agreed that any dealings betw...
5   Executed by the parties or their respective du...
6   For and on behalf of Barclays: For and on beha...
7   The terms Controlling and Controlled shall hav...
8   2 Confidential Information 2.1 The Receiving P...
9   2.2 The Receiving Party shall only use the Con...
10  2.3 Notwithstanding clauses 2.1 and 2.2, the R...
11  2.4 The Receiving Party shall at all times rem...
12  2.5 If any Confidential Information is copied,...
13  2.6 Notwithstanding whether or not the Receivi...
14  2.7 The Disclosing Party warrants and represen...
15  2.8 If there is a change of Control of the Cou...
16  3 Exceptions 3.1 The provisions of clause 2 (C...
17  3.2 Confidential Information shall not be exem...
18  4 Records and return of information 4.1 The Re...
19  The Receiving Party shall not make any copies ...

In [21]:
df.loc[0, "label"] = "Confidentiality"
df.loc[1, "label"] = "Termination"
df.loc[2, "label"] = "Payment"
df.loc[3, "label"] = "Liability"
df.loc[4, "label"] = "Other"

In [22]:
df.to_csv("../data/datasets/labeled_clauses.csv", index=False)

print("Labeled dataset saved")

Labeled dataset saved

In [23]:
df = df[df["clause"].str.strip() != ""]

In [24]:
df.head()

                                              clause            label
0  Mutual NDA – revised 4 May 2018 1 Barclays Com...  Confidentiality
1  A separate contract will be required whenever:...      Termination
2  Barclays: Name and company registration number...          Payment
3  “Evaluations by Barclays of the Counterparty’s...        Liability
4  The parties have agreed that any dealings betw...            Other

In [25]:
df = df[df["label"] != ""]

In [26]:
X = df["clause"]
y = df["label"]

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_vectorized = vectorizer.fit_transform(X)

In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_vectorized, y)

LogisticRegression()

In [29]:
sample_clause = ["Payment must be completed within 30 days"]

sample_vector = vectorizer.transform(sample_clause)

prediction = model.predict(sample_vector)

print("Predicted Label:", prediction[0])

Predicted Label: Termination

In [30]:
df.loc[0, "label"] = "Confidentiality"
df.loc[1, "label"] = "Termination"
df.loc[2, "label"] = "Payment"
df.loc[3, "label"] = "Liability"
df.loc[4, "label"] = "Other"

df.loc[5, "label"] = "Confidentiality"
df.loc[6, "label"] = "Termination"
df.loc[7, "label"] = "Payment"
df.loc[8, "label"] = "Liability"
df.loc[9, "label"] = "Other"

df.loc[10, "label"] = "Confidentiality"
df.loc[11, "label"] = "Termination"
df.loc[12, "label"] = "Payment"
df.loc[13, "label"] = "Liability"
df.loc[14, "label"] = "Other"

df.loc[15, "label"] = "Confidentiality"
df.loc[16, "label"] = "Termination"
df.loc[17, "label"] = "Payment"
df.loc[18, "label"] = "Liability"
df.loc[19, "label"] = "Other"

print("Labels added successfully")

Labels added successfully

In [31]:
new_rows = pd.DataFrame({
    "clause": [
        "Payment must be made within 30 days",
        "The client shall pay the amount before due date",
        "Invoice payment is required within 15 days",
        "All payments shall be completed electronically",
        "Late payment charges will apply"
    ],
    "label": [
        "Payment",
        "Payment",
        "Payment",
        "Payment",
        "Payment"
    ]
})

df = pd.concat([df, new_rows], ignore_index=True)

print("Payment samples added")

Payment samples added

In [32]:
# Remove empty labels
df = df[df["label"] != ""]

# Remove empty clauses / NaN values
df = df.dropna(subset=["clause"])

# Convert clauses to string
df["clause"] = df["clause"].astype(str)

# Prepare training data
X = df["clause"]
y = df["label"]

# TF-IDF Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_vectorized = vectorizer.fit_transform(X)

# Train model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_vectorized, y)

# Test prediction
sample_clause = ["Payment must be completed within 30 days"]

sample_vector = vectorizer.transform(sample_clause)

prediction = model.predict(sample_vector)

print("Predicted Label:", prediction[0])

Predicted Label: Payment

In [33]:
import pickle

# Save model
with open("../models/clause_model.pkl", "wb") as file:
    pickle.dump(model, file)

# Save vectorizer
with open("../models/vectorizer.pkl", "wb") as file:
    pickle.dump(vectorizer, file)

print("Model and vectorizer saved successfully")

Model and vectorizer saved successfully

In [34]:
import pickle

# Load saved model
with open("../models/clause_model.pkl", "rb") as file:
    loaded_model = pickle.load(file)

# Load saved vectorizer
with open("../models/vectorizer.pkl", "rb") as file:
    loaded_vectorizer = pickle.load(file)

# Test prediction
sample_clause = ["Confidential information must not be shared"]

sample_vector = loaded_vectorizer.transform(sample_clause)

prediction = loaded_model.predict(sample_vector)

print("Predicted Label:", prediction[0])

Predicted Label: Payment

<h1> More Accurate Version <h1>

In [35]:
training_data = pd.DataFrame({
    "clause": [

        # Payment
        "Payment must be completed within 30 days",
        "Invoice payment is required within 15 days",
        "Late payment charges will apply",
        "The client shall pay all fees on time",
        "All payments shall be processed electronically",

        # Confidentiality
        "Confidential information must not be disclosed",
        "Both parties agree to maintain confidentiality",
        "The employee shall not share trade secrets",
        "Sensitive company data must remain private",
        "Disclosure of confidential material is prohibited",

        # Termination
        "Either party may terminate this agreement",
        "The contract may be terminated with notice",
        "Termination requires 30 days prior notice",
        "This agreement shall end upon breach",
        "The company reserves the right to terminate",

        # Liability
        "The company shall not be liable for damages",
        "Neither party accepts unlimited liability",
        "Liability is limited under this agreement",
        "The vendor assumes all legal responsibility",
        "Damages shall be compensated accordingly",

        # Other
        "This agreement is governed by applicable law",
        "The parties agree to the stated conditions",
        "This contract becomes effective immediately",
        "The agreement shall remain legally binding",
        "All amendments must be documented"
    ],

    "label": [

        "Payment",
        "Payment",
        "Payment",
        "Payment",
        "Payment",

        "Confidentiality",
        "Confidentiality",
        "Confidentiality",
        "Confidentiality",
        "Confidentiality",

        "Termination",
        "Termination",
        "Termination",
        "Termination",
        "Termination",

        "Liability",
        "Liability",
        "Liability",
        "Liability",
        "Liability",

        "Other",
        "Other",
        "Other",
        "Other",
        "Other"
    ]
})

df = pd.concat([df, training_data], ignore_index=True)

print("Training data added successfully")

Training data added successfully

In [36]:
# Remove missing values
df = df.dropna(subset=["clause", "label"])

# Convert to string
df["clause"] = df["clause"].astype(str)

# Prepare data
X = df["clause"]
y = df["label"]

# Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

X_vectorized = vectorizer.fit_transform(X)

# Train model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_vectorized, y)

print("Model retrained successfully")

Model retrained successfully

In [37]:
sample_clause = ["Confidential information must not be shared"]

sample_vector = vectorizer.transform(sample_clause)

prediction = model.predict(sample_vector)

print("Predicted Label:", prediction[0])

Predicted Label: Confidentiality

<h1>Risk Detection<h1>

In [38]:
risk_data = pd.DataFrame({"clause": [

        # High Risk
        "The company accepts unlimited liability",
        "The client may terminate immediately without notice",
        "All legal responsibility falls on the vendor",
        "The employee is liable for all damages",
        "Confidential information may be shared publicly",

        # Medium Risk
        "The agreement renews automatically every year",
        "Late payment penalties may apply",
        "Termination requires a short notice period",
        "Additional charges may be added later",
        "The service terms may change without warning",

        # Low Risk
        "Payment must be completed within 30 days",
        "Both parties agree to maintain confidentiality",
        "The contract may be terminated with prior notice",
        "All amendments must be documented",
        "The agreement follows standard company policy"
    ],

    "risk": [

        "High Risk",
        "High Risk",
        "High Risk",
        "High Risk",
        "High Risk",

        "Medium Risk",
        "Medium Risk",
        "Medium Risk",
        "Medium Risk",
        "Medium Risk",

        "Low Risk",
        "Low Risk",
        "Low Risk",
        "Low Risk",
        "Low Risk"
    ]
})

print(risk_data.head())

                                              clause       risk
0            The company accepts unlimited liability  High Risk
1  The client may terminate immediately without n...  High Risk
2       All legal responsibility falls on the vendor  High Risk
3             The employee is liable for all damages  High Risk
4    Confidential information may be shared publicly  High Risk

In [39]:
# Prepare risk training data
X_risk = risk_data["clause"]
y_risk = risk_data["risk"]

# Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

risk_vectorizer = TfidfVectorizer()

X_risk_vectorized = risk_vectorizer.fit_transform(X_risk)

# Train model
from sklearn.linear_model import LogisticRegression

risk_model = LogisticRegression(max_iter=1000)

risk_model.fit(X_risk_vectorized, y_risk)

print("Risk Detection Model trained successfully")

Risk Detection Model trained successfully

In [40]:
sample_clause = ["The company accepts unlimited liability"]

sample_vector = risk_vectorizer.transform(sample_clause)

prediction = risk_model.predict(sample_vector)

print("Predicted Risk:", prediction[0])

Predicted Risk: High Risk

In [41]:
import pickle

# Save risk model
with open("../models/risk_model.pkl", "wb") as file:
    pickle.dump(risk_model, file)

# Save risk vectorizer
with open("../models/risk_vectorizer.pkl", "wb") as file:
    pickle.dump(risk_vectorizer, file)

print("Risk model and vectorizer saved successfully")

Risk model and vectorizer saved successfully

In [42]:
import pickle

# Load saved risk model
with open("../models/risk_model.pkl", "rb") as file:
    loaded_risk_model = pickle.load(file)

# Load saved risk vectorizer
with open("../models/risk_vectorizer.pkl", "rb") as file:
    loaded_risk_vectorizer = pickle.load(file)

# Test prediction
sample_clause = ["The employee is liable for all damages"]

sample_vector = loaded_risk_vectorizer.transform(sample_clause)

prediction = loaded_risk_model.predict(sample_vector)

print("Predicted Risk:", prediction[0])

Predicted Risk: High Risk

In [43]:
import spacy

nlp = spacy.load("en_core_web_sm")

print("spaCy model loaded successfully")

spaCy model loaded successfully

In [44]:
sample_text = """
ABC Pvt Ltd will pay ₹50000 to XYZ Solutions on January 10, 2026 in Mumbai.
"""

doc = nlp(sample_text)

for ent in doc.ents:
    print(ent.text, "→", ent.label_)

ABC Pvt Ltd → ORG
50000 → MONEY
XYZ Solutions → ORG
January 10, 2026 → DATE
Mumbai → GPE

In [1]:
from transformers import pipeline

summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

print("Summarizer loaded successfully")

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

C:\Users\stwks\anaconda3\envs\contract_ai\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\stwks\.cache\huggingface\hub\models--facebook--bart-large-cnn. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Summarizer loaded successfully

In [2]:
sample_contract = """
This agreement is made between ABC Pvt Ltd and XYZ Solutions.
The client agrees to complete payment within 30 days.
Both parties agree to maintain confidentiality of sensitive information.
The agreement may be terminated with prior written notice.
The company shall not be liable for indirect damages.
"""

summary = summarizer(
    sample_contract,
    max_length=60,
    min_length=20,
    do_sample=False
)

print(summary[0]['summary_text'])

This agreement is made between ABC Pvt Ltd and XYZ Solutions. Both parties agree to maintain confidentiality of sensitive information.

In [47]:
def analyze_contract(text):

    # Clean text
    cleaned = clean_text(text)

    # Split clauses
    clauses = split_clauses(cleaned)

    print("\n--- Clause Classification ---")

    for clause in clauses[:5]:

        clause_vector = vectorizer.transform([clause])

        clause_prediction = model.predict(clause_vector)

        print(f"\nClause: {clause}")
        print("Type:", clause_prediction[0])

    print("\n--- Risk Detection ---")

    for clause in clauses[:5]:

        risk_vector = risk_vectorizer.transform([clause])

        risk_prediction = risk_model.predict(risk_vector)

        print(f"\nClause: {clause}")
        print("Risk:", risk_prediction[0])

    print("\n--- Named Entities ---")

    doc = nlp(text)

    for ent in doc.ents:
        print(ent.text, "→", ent.label_)

    print("\n--- Summary ---")

    summary = summarizer(
        text[:2000],
        max_length=60,
        min_length=20,
        do_sample=False
    )

    print(summary[0]['summary_text'])

In [48]:
analyze_contract(contract_text)

--- Clause Classification ---

Clause: Mutual NDA – revised 4 May 2018 1 Barclays Commercial, Innovation & Technology Legal ______________________________________ NON-DISCLOSURE AGREEMENT ______________________________________ Note: This document is a Non-Disclosure Agreement only
Type: Confidentiality

Clause: A separate contract will be required whenever: - goods or services are being provided by or to Barclays; - any payment is being made by or to Barclays; - any personal data is being transferred by or to Barclays; or - any intellectual property is being created or licensed by either party to the other (including any rights to use Barclays’ name or logo)
Type: Termination

Clause: Barclays: Name and company registration number: (choose the applicable Barclays contracting entity) Registered address: 1 Churchill Place, London, E14 5HP Counterparty: Name: (Full corporate or personal name of other party) Registered address: (or home address where individual) Country of registration: (leave blank where counterparty is an individual) Company registration number: (leave blank where counterparty is an individual) Effective Date: (Date from which information is first being disclosed under this agreement – this can start before, after or on the date of signature) Project: (Details of the proposal/project to which this agreement applies, e.g
Type: Payment

Clause: “Evaluations by Barclays of the Counterparty’s [X] product”, “Discussions for the development of an alternative [Y] system”, “Discussions on how Barclays can collaborate with [X] for the purposes of [Y]”) Barclays and the Counterparty have entered into discussions regarding the Project and it is envisaged that each party may from time to time receive Information (as defined below) relating to the other in respect thereof
Type: Liability

Clause: The parties have agreed that any dealings between them shall be subject to this Agreement, the terms of which are contained on the following pages
Type: Other

--- Risk Detection ---

Clause: Mutual NDA – revised 4 May 2018 1 Barclays Commercial, Innovation & Technology Legal ______________________________________ NON-DISCLOSURE AGREEMENT ______________________________________ Note: This document is a Non-Disclosure Agreement only
Risk: Medium Risk

Clause: A separate contract will be required whenever: - goods or services are being provided by or to Barclays; - any payment is being made by or to Barclays; - any personal data is being transferred by or to Barclays; or - any intellectual property is being created or licensed by either party to the other (including any rights to use Barclays’ name or logo)
Risk: Low Risk

Clause: Barclays: Name and company registration number: (choose the applicable Barclays contracting entity) Registered address: 1 Churchill Place, London, E14 5HP Counterparty: Name: (Full corporate or personal name of other party) Registered address: (or home address where individual) Country of registration: (leave blank where counterparty is an individual) Company registration number: (leave blank where counterparty is an individual) Effective Date: (Date from which information is first being disclosed under this agreement – this can start before, after or on the date of signature) Project: (Details of the proposal/project to which this agreement applies, e.g
Risk: High Risk

Clause: “Evaluations by Barclays of the Counterparty’s [X] product”, “Discussions for the development of an alternative [Y] system”, “Discussions on how Barclays can collaborate with [X] for the purposes of [Y]”) Barclays and the Counterparty have entered into discussions regarding the Project and it is envisaged that each party may from time to time receive Information (as defined below) relating to the other in respect thereof
Risk: High Risk

Clause: The parties have agreed that any dealings between them shall be subject to this Agreement, the terms of which are contained on the following pages
Risk: Low Risk

--- Named Entities ---
4 → CARDINAL
May 2018 → DATE
1 → CARDINAL
Barclays Commercial, Innovation & Technology Legal → ORG
1 → CARDINAL
London → GPE
first → ORDINAL
Counterparty → ORG
Counterparty → ORG
Project → ORG
Counterparty → ORG
Barclays Services Limited → ORG
Barclays Bank PLC → ORG
Barclays Bank UK PLC → ORG
Mutual NDA → PERSON
4 → CARDINAL
May 2018 → DATE
2 → CARDINAL
Barclays Commercial, Innovation & Technology Legal
TERMS OF NON-DISCLOSURE → ORG
1 → CARDINAL
1.1 → CARDINAL
Affiliate → ORG
Control of → ORG
Confidential Information means Information → ORG
one → CARDINAL
Related Parties (Disclosing Party → ORG
the Disclosing Party → ORG
Project → ORG
Receiving Party → ORG
the
Disclosing Party → ORG
the Effective Date → ORG
the Receiving Party → ORG
more than 30% → PERCENT
second → ORDINAL
second → ORDINAL
Intellectual Property Rights → ORG
Intellectual Property Rights → ORG
Project → ORG
Related Party → ORG
Affiliate → ORG
2 → CARDINAL
2.1 → CARDINAL
The Receiving Party → ORG
the Disclosing Party’s → ORG
Confidential Information → ORG
2.2 → CARDINAL
The Receiving Party → ORG
the Confidential
Information → ORG
2.3 → CARDINAL
2.1 → CARDINAL
2.2 → DATE
the Receiving Party → ORG
Confidential Information → ORG
2.8 → CARDINAL
the Confidential Information → ORG
Confidential Information → ORG
the Receiving Party → ORG
2.4 → CARDINAL
The Receiving Party → ORG
Confidential Information → ORG
2.5 → CARDINAL
Confidential Information → ORG
the Disclosing
Party → ORG
the Receiving Party → ORG
the Disclosing Party → ORG
the Disclosing Party → ORG
2.6 → CARDINAL
the Receiving Party → ORG
Affiliate → ORG
Related Party → ORG
the Confidential
Information → ORG
Confidential
Information → WORK_OF_ART
Confidential Information → ORG
the Disclosing Party → ORG
the Receiving Party → ORG
the Disclosing Party → ORG
the Confidential
Information → ORG
2.7 → CARDINAL
The Disclosing Party → ORG
the Confidential
Information → ORG
the Receiving Party → ORG
2.8 → CARDINAL
Control of the Counterparty → ORG
Barclays Competitor → ORG
Counterparty → ORG
Confidential Information → ORG
3 → CARDINAL
3.1 → CARDINAL
2 → CARDINAL
Confidential Information → ORG
Confidential Information → ORG
the Receiving Party → ORG
the Receiving
Party → ORG
Mutual NDA → PERSON
4 → CARDINAL
May 2018 → DATE
3 → CARDINAL
Barclays Commercial, Innovation & Technology Legal → ORG
the Disclosing
Party → ORG
the Receiving
Party → ORG
the Disclosing Party → ORG
the Disclosing Party → ORG
the Receiving Party → ORG
the Receiving Party → ORG
the Disclosing Party → ORG
3.2 → CARDINAL
Confidential Information → ORG
3.1 → CARDINAL
2 → CARDINAL
Confidential Information → ORG
the
Receiving Party → ORG
3.1 → CARDINAL
the Receiving Party → ORG
3.1 → CARDINAL
4 → CARDINAL
4.1 → CARDINAL
The Receiving Party → ORG
Confidential Information → ORG
the Receiving Party → ORG
Confidential Information → ORG
The Receiving Party → ORG
Confidential Information → ORG
4.2 → CARDINAL
The Receiving Party → ORG
the Disclosing Party → ORG
Confidential Information → ORG
Confidential Information → ORG
4.3 → CARDINAL
The Receiving Party → ORG
seven days → DATE
the Disclosing Party → ORG
Confidential Information → ORG
the Receiving
Party → ORG
2.3 → CARDINAL
4.4 → CARDINAL
4.3 → CARDINAL
Confidential
Information → ORG
Agreement → PRODUCT
Confidential Information → ORG
4.5 → CARDINAL
The Receiving Party → ORG
4.3 → CARDINAL
4.4 → CARDINAL
5 → CARDINAL
5.1 → CARDINAL
Project → ORG
5.2 → CARDINAL
6 → CARDINAL
Project → ORG
3.1(a → CARDINAL
3.1(d → CARDINAL
3.2 → CARDINAL
five years → DATE
the
Disclosing Party → ORG
7.1 → CARDINAL
the Receiving Party → ORG
Project → ORG
the Disclosing Party → ORG
7.2 → CARDINAL
2.7 → CARDINAL
the Disclosing Party → ORG
the Receiving Party → ORG
8 → CARDINAL
8.1 → CARDINAL
the
Disclosing Party → ORG
Receiving Party → ORG
Disclosing Party → ORG
the Receiving Party → ORG
9.1 → CARDINAL
9.2 → CARDINAL
1999 → DATE
9.2 → CARDINAL
the Receiving Party → ORG
Agreement → PRODUCT
the Disclosing Party → ORG
Affiliates → ORG
1999 → DATE
the Disclosing
Party → ORG
the Receiving Party’s → ORG
9.3 → CARDINAL
Agreement → PRODUCT
4 → CARDINAL
May 2018 → DATE
4 → CARDINAL
Barclays Commercial, Innovation & Technology Legal
Contracts (Rights of Third Parties → ORG
1999 → DATE
10 → CARDINAL
10.1 → CARDINAL
Barclays → ORG
Agreement → PRODUCT
Affiliates → ORG
10.2 → CARDINAL
one → CARDINAL
PDF → ORG
10.3 → CARDINAL
10.4 → CARDINAL
10.5 → CARDINAL
10.6 → CARDINAL
This Agreement → WORK_OF_ART
10.7 → CARDINAL
Agreement → PRODUCT
10.8 → CARDINAL
English → LANGUAGE
English → NORP
more than one → CARDINAL

--- Summary ---
Barclays and the Counterparty have entered into discussions regarding the Project and it is envisaged that each party may from time to time receive Information (as defined below) relating to the other. The parties have agreed that any dealings between them shall be subject to this Non-Disclosure